ARG MONGOOSE_NFS_DRIVER_VERSION

FROM emcmongoose/mongoose-storage-driver-nfs:${MONGOOSE_NFS_DRIVER_VERSION}

EXPOSE 1099

ENTRYPOINT ["/usr/bin/mongoose", "-jar", "/opt/mongoose/mongoose-storage-driver-service.jar"]
